#!/usr/bin/env bash
# Displays Information about subdomains

# shellcheck disable=SC2086

# Usage:
# (1) ./0-world_wide_web 3akare.tech
# (2) ./0-world_wide_web 3akare.tech web-02

if [ "$#" -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${subdomains[@]}"; do
        result=$(dig "$sub_domain.$1" +short)
        if [ -n "$result" ]; then
            record_type=$(dig "$sub_domain.$1" | awk '/ANSWER SECTION/{getline; print $4}')
            ip_address=$(dig "$sub_domain.$1" | awk '/ANSWER SECTION/{getline; print $5}')
            echo "The subdomain $sub_domain is a $record_type record and points to $ip_address"
        fi
    done
elif [ "$#" -eq 2 ]; then
    result=$(dig "$2.$1" +short)
    if [ -n "$result" ]; then
        record_type=$(dig "$2.$1" | awk '/ANSWER SECTION/{getline; print $4}')
        ip_address=$(dig "$2.$1" | awk '/ANSWER SECTION/{getline; print $5}')
        echo "The subdomain $2 is a $record_type record and points to $ip_address"
    fi
fi
