#!/usr/bin/env bash
# Use scp to transfer a file from a client to a server

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=${4:-}

if [ -z "$SSH_KEY" ]; then
    scp -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
else
    scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
fi
