#!/usr/bin/env bash
# Script to double the number of web servers and add new configurations

apt-get update
apt-get -y install nginx

config_string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$config_string/" /etc/nginx/nginx.conf

sudo service nginx restart
