#!/usr/bin/env bash
# Configure nginx to listen on port 80 and start the service
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo systemctl start nginx
sudo kill "$(pgrep nginx | head -n 1)"
