#!/usr/bin/env bash

# Process and PID file
file="/var/run/myscript.pid"

# Create the PID file if it doesn't exist
if [ ! -e "$file" ]; then
  touch "$file"
fi

# Start a background process to sleep for 2 seconds
sleep 2 &

# Write the PID of the background process to the PID file
echo "$!" > "$file"

# Handle SIGTERM and SIGQUIT signals
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

# Handle SIGINT signal
trap 'echo "Y U no love me?!"' SIGINT

# Print message indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 2
done
