#!/usr/bin/env bash
# Function to handle SIGTERM signal
handle_sigterm() 
{
    echo "I am invincible!!!"
    exit 0
}

# Trap SIGTERM signal
trap 'handle_sigterm' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
