#!/usr/bin/env bash
# The following script shows the information of users from the file `/etc/passwd`.
# It specifically displays the username, user id, and user home directory path.

passwd_file="/etc/passwd"
while IFS= read -r entry
do
    echo "$entry" | cut -d":" -f1,3,6
done < "$passwd_file"
