#!/usr/bin/env bash
# A script that displays "Best School" 10 times and "Hi" 
after the 9th iteration using a while loop and an if statement

count=1

while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    ((count++))
done
