#!/usr/bin/env bash
# A script that displays different messages based on loop 
iteration using a while loop and if-elif-else statements

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
