#!/usr/bin/env bash
# A script that displays numbers and corresponding messages 
based on loop iteration using a while loop and a case statement

counter=1

while [ $counter -le 20 ]
do
  echo "$counter"
  case $counter in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( counter++ ))
done
