#!/usr/bin/env bash

current_hour=0

while [ $current_hour -le 12 ]
do
  echo "Hour: $current_hour"
  current_minute=1
  while [ $current_minute -le 59 ]
  do
    echo "$current_minute"
    (( current_minute++ ))
  done
  (( current_hour++ ))
done
