#!/usr/bin/env bash
# This script provides information about the school file.

# Check if the "school" file exists
file=./school

if [ -e "$file" ]; then
    echo "The 'school' file exists"
    
    # Check if the file is empty
    if [ -s "$file" ]; then
        echo "The 'school' file is not empty"
    else
        echo "The 'school' file is empty"
    fi
    
    # Check if the file is a regular file
    if [ -f "$file" ]; then
        echo "The 'school' is a regular file"
    fi
else
    echo "The 'school' file does not exist"
fi
