#!/usr/bin/env bash

# Bash script that fulfills the specified requirements for configuring an Ubuntu server.
# Modify the hosts file to set localhost to resolve to 127.0.0.2 and facebook.com to resolve to 8.8.8.8.

cp /etc/hosts ~/hosts.new
echo "127.0.0.2    localhost" > ~/hosts.new
echo "8.8.8.8    facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
