#!/usr/bin/env bash
# Configures a web server to run Nginx as the nginx user on port 8080.

# Update the nginx.conf file to set the user to 'nginx' by replacing '#user www-data'
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change the port in the default site configuration from 80 to 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Set the permissions of the nginx.conf file to be readable and writable by the owner
chmod 644 /etc/nginx/nginx.conf

# Terminate any running Apache processes to avoid conflicts with Nginx
pkill apache2

# Start the Nginx service as the nginx user
sudo -u nginx service nginx start

