#!/usr/bin/env bash
# Configures the web server to run Nginx as the nginx user on port 8080.

# Modify the Nginx configuration to set the user to 'nginx'
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change the default listening port to 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Set the correct permissions for the Nginx configuration file
chmod 644 /etc/nginx/nginx.conf

# Stop Apache to prevent conflicts with Nginx
pkill apache2

# Start Nginx as the nginx user
sudo -u nginx service nginx start
